behaviors:
  Dodge:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1028 # 256
      buffer_size: 20480  # 1024   4096
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3  # 3
      learning_rate_schedule: linear
      #beta_schedule: constant
      #epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2  # default 2
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99    # 0.99   95 seems good for simple task,   80 was the best result  hmmm
    max_steps: 988400000 #440000 5 min   1000000 20 min   changes depending on the amount of agents
    time_horizon: 2048  # 64
    summary_freq: 80000
    threaded: true