behaviors:
  MoveToGoal:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512 
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        strength: 0.1
        gamma: 0.80 
      gail: 
        strength: 1.0
        gamma: 0.80
        demo_path: Demos/FoodAgentDemo.demo
    behavioral_cloning:
      strength: 1.0
      gamma: 0.80
      demo_path: Demos/FoodAgentDemo.demo
    max_steps: 440000 #440000 5 min   1000000 20 min
    time_horizon: 64
    summary_freq: 20000
    threaded: true