behaviors:
  MoveToGoal:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512 # 256
      buffer_size: 10240  # 1024   4096
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3  #3 don't be fooled, timestep doesn't mean it's faster if each timestep takes longer to compute, an epoch of 3 in a situation can give faster results
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2  # default 2
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.80    # 0.99   Very shaky below 80,   80-95 is good range
    max_steps: 4400000 #440000 5 min   1000000 20 min
    time_horizon: 64
    summary_freq: 20000
    threaded: true