behaviors:
  NavigateToGoal:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512 
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        strength: 0.7
        gamma: 0.99 
      curiosity: 
        strength: 0.2
        gamma: 0.99
    max_steps: 44000000 #440000 5 min   1000000 20 min
    time_horizon: 64
    summary_freq: 20000
    threaded: true